version: '3.8'

services:
  postgres:
      image: postgres:15-alpine
      container_name: pokeforge_postgres
      restart: always
      environment:
        POSTGRES_USER: forge_admin
        POSTGRES_PASSWORD: forge_secure_password123
        POSTGRES_DB: pokeforge
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./migrations:/docker-entrypoint-initdb.d
      networks:
        - pokeforge_network

volumes:
  pgdata:

networks:
  pokeforge_network:
    driver: bridge

